spring:
  data:    mongodb:      database: mongo-db-connection
      uri: ${smaple-mongdb-connection-string}

azure:
  keyvault:
    enabled: true
    uri: https://smaplekeyvaluts.vault.azure.net/
    client-id: 368c968f-707e-4583-a503-d32bfb57684d
    client-key: pMh7Q~tkE6.hxWKVG1Ho3oPjushbq0hPE5s6U
    tenant-id: 9d16c0e6-6f00-473a-9471-16ac116587b5
    token-acquire-timeout-secounds: 60
    refresh-interval: 1800000

server:
  port: 8440